version: '3.8'
services:
  api:
    container_name: api
    build: ./
    ports:
      - 5000:5000
    environment:
      DATABASE_URL: postgres://postgres:adminPasword@db:5432/hackernews
  db:
    container_name: db
    image: postgres:13.1
    ports:
      - 5432:5432
    volumes: 
      - ./postgresdata:/var/lib/postgresql/data
      - ./BD/bd.sql:/docker-entrypoint-initdb.d/dbinit.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminPasword
      POSTGRES_DB: hackernews
volumes:
    db-data:
    
